# Generated by Django 2.0.1 on 2018-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballots',
            fields=[
                ('candidate_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('json', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ballots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeHistory',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('effective', models.DateField(blank=True, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('filing_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'committee_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteesList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filer_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'committees_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_type', models.CharField(blank=True, max_length=32, null=True)),
                ('donor_cats', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElectionActivity',
            fields=[
                ('election', models.CharField(blank=True, max_length=64, null=True)),
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('active_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('active_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'election_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('payee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payee_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementOfOrg',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_address', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_acronym', models.CharField(blank=True, max_length=32, null=True)),
                ('committee_address', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_campaign_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('committee_filing_effective_from', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_filing_type', models.CharField(blank=True, max_length=10, null=True)),
                ('committee_pac_type', models.CharField(blank=True, max_length=32, null=True)),
                ('election_office', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=32, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('party_affiliation', models.CharField(blank=True, max_length=16, null=True)),
                ('treasurer_email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_fax', models.CharField(blank=True, max_length=32, null=True)),
                ('treasurer_home_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('treasurer_mailing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_work_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'statement_of_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payee_id', models.IntegerField(blank=True, null=True)),
                ('donor_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_book_type', models.CharField(blank=True, max_length=32, null=True)),
                ('agent', models.CharField(blank=True, max_length=64, null=True)),
                ('aggregate', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('associations', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation_letter_date', models.DateField(blank=True, null=True)),
                ('payer_of_personal_expenditure', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('process_status', models.CharField(blank=True, max_length=32, null=True)),
                ('purpose', models.CharField(blank=True, max_length=512, null=True)),
                ('repayment_schedule', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_sub_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'transaction_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('committee_id', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('filer_committee', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_payee', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_subtype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
