# Generated by Django 2.0.1 on 2018-06-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalContributions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'total_contributions',
                'managed': False,
            },
        ),
    ]
