# Generated by Django 2.0.1 on 2018-06-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_totalcontributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'election_cycles',
                'managed': False,
            },
        ),
    ]
