# Generated by Django 2.0.1 on 2018-06-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_electioncycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalContributionsMonthly',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalContributionsYearly',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw_year',
                'managed': False,
            },
        ),
    ]
