# Generated by Django 2.0.1 on 2018-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_totalcontributionsmonthly_totalcontributionsyearly'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalContributionsRawInState',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw_in_state',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='totalcontributions',
            table='total_contributions_raw',
        ),
    ]
