# Generated by Django 2.0.1 on 2018-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180614_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorBreakdown',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'contributor_breakdown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalContributionsRawMonthRaceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('race_type', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw_month_race_type',
                'managed': False,
            },
        ),
    ]
