# Generated by Django 2.0.1 on 2018-06-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contributorbreakdown_totalcontributionsrawmonthracetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contributor_payee', models.CharField(blank=True, max_length=255, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'committee_contributions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpendingBreakdown',
            fields=[
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('spending_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spending_breakdown',
                'managed': False,
            },
        ),
    ]
