# Generated by Django 2.0.1 on 2019-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_committeecontributors_spendingbreakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeElectionCycle',
            fields=[
                ('committee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'committee_election_cycle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContributorGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalContributionsRaw',
            fields=[
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalContributionsRawMonthTotal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'total_contributions_raw_month_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoterAcquisitionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_acquisition_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('votes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('election_cycle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'voter_acquisition_cost',
                'managed': False,
            },
        ),
    ]
