from django.db import models

class oreStarData(models.Model):
    tran_id = models.IntegerField()
    original_id = models.IntegerField()
    tran_date = models.DateField()
    tran_status = models.CharField()
    filer = models.CharField()
    payee = models.CharField()
    subtype = models.CharField()
    amount = models.FloatField()
    agg_amount = models.FloatField()
    payee_id = models.IntegerField()
    filer_id = models.IntegerField()
    attest_by_name = models.CharField()
    attest_date= models.DateField()
    review_by_name = models.CharField()
    review_date = models.DateField()
    due_date = models.DateField()
    occptn_ltr_date = models.CharField()
    payment_text = models.CharField()
    purps_desc = models.CharField()
    intrst_rate = models.IntegerField()
    check_numb = models.IntegerField()
    trans_status_ind = models.BooleanField()
    file_by_name = models.CharField()
    file_date = models.DateField()
    addr_book_agent = models.CharField()
    book_type = models.CharField()
    title_txt = models.CharField()
    occptn_txt = models.CharField()
    emp_name = models.CharField()
    emp_city = models.CharField()
    emp_state = models.CharField()
    emploeed_ind = models.BooleanField()
    self_employee_ind = models.BooleanField()
    addr_line_1 = models.CharField()
    addr_line_2 = models.CharField()
    city = models.CharField()
    state = models.CharField()
    zipcode = models.IntegerField()
    zipplus = models.IntegerField()
    county = models.CharField()
    purpose_code = models.CharField()

    class Meta:
        db_table = 'OreStar Data Scrape'
        managed = True
        verbose_name = 'ModelName'
        verbose_name_plural = 'ModelNames'