from rest_framework import serializers
from .models import oreStarData

class oreStarSerializer(serializers.ModelSerializer):
    class Meta:
        model = oreStarData
        fields = (
            'tran_id',
            'original_id',
            'tran_date',
            'tran_status',
            'filer',
            'payee',
            'subtype',
            'amount',
            'agg_amount',
            'payee_id',
            'filer_id',
            'attest_by_name',
            'attest_date',
            'review_by_name',
            'review_date',
            'due_date',
            'occptn_ltr_date',
            'payment_text',
            'purps_desc',
            'intrst_rate',
            'check_numb',
            'trans_status_ind',
            'file_by_name',
            'file_date',
            'addr_book_agent',
            'book_type',
            'title_txt',
            'occptn_txt',
            'emp_name',
            'emp_city',
            'emp_state',
            'emploeed_ind',
            'self_employee_ind',
            'addr_line_1',
            'addr_line_2',
            'city',
            'state',
            'zipcode',
            'zipplus',
            'county',
            'purpose_code',
        )